# Generated by Django 4.2.15 on 2024-08-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('availableLocalCurrency', models.CharField(default='N/A', max_length=255)),
                ('cityName', models.CharField(default='Unknown', max_length=255)),
                ('districtName', models.CharField(max_length=255)),
                ('streetAddress', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
    ]
